### ISSUE TITLE
comparison with serverless approach (docs)

### ISSUE THREAD

**Issue by greaber** [torrvision/crayon#35]
I started using crayon in my project, and I have been reasonably happy with it although it is a pity that it doesn't support all tensorboard summary types and that it does not seem to be very actively maintained.  Later I discovered a different approach of just using a client library to create tensorboard log items (see https://github.com/TeamHG-Memex/tensorboard_logger and, for a particularly simple approach, https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/04-utils/tensorboard/logger.py).  I realize that the crayon approach is in a way more flexible since it provides a REST api, but for someone just looking to use tensorboard with pytorch, it is not very clear what the advantages of crayon are over a simpler approach not using a separate server, given that no solution seems to be under active maintenance.

**Comment by albanD** [comment]
Hi,
There were two main reason to have it as a server:
* you dont have to install tensorflow/tensorboard on all your machines but just one, and use a single machine for logging.
* it is possible to make clients for various languages very easily: we needed both lua and python support in our case.

**Comment by greaber** [comment]
OK, thanks for the explanation, it is helpful.

**Comment by greaber** [comment]
I closed, but it could be worth adding this to the README.
